version: '3.8'

services:
  # Zookeeper (Required by Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  # Kafka Broker
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - kafka-network

  # Kafka UI (Web Interface)
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - kafka-network

  # PostgreSQL (for Order Service)
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Add init script for all databases
      - ./init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql
    networks:
      - kafka-network

  # MongoDB (for Inventory Service)
  mongodb:
    image: mongo:6-jammy
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - kafka-network

  # Redis (for Caching)
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - kafka-network

  # Zipkin for Distributed Tracing
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - kafka-network

  
networks:
  kafka-network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
  nginx.config:


#  auth-service:
#      build: ./auth-service
#      container_name: auth-service
#      ports:
#        - "8084:8084"
#      environment:
#        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/authdb
#        SPRING_ZIPKIN_BASE_URL: http://zipkin:9411
#      depends_on:
#        - postgres
#        - zipkin
#      networks:
#        - kafka-network
#
#    order-service:
#      build: ./order-service
#      container_name: order-service
#      ports:
#        - "8081:8081"
#      environment:
#        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/orderdb
#        SPRING_ZIPKIN_BASE_URL: http://zipkin:9411
#      depends_on:
#        - kafka
#        - postgres
#        - zipkin
#      networks:
#        - kafka-network
#    
#    inventory-service:
#      build: ./inventory-service
#      container_name: inventory-service
#      ports:
#        - "8082:8082"
#      environment:
#        SPRING_ZIPKIN_BASE_URL: http://zipkin:9411
#      depends_on:
#        - kafka
#        - mongodb
#        - zipkin
#      networks:
#        - kafka-network
#    
#    notification-service:
#      build: ./notification-service
#      container_name: notification-service
#      ports:
#        - "8083:8083"
#      environment:
#        SPRING_ZIPKIN_BASE_URL: http://zipkin:9411
#      depends_on:
#        - kafka
#        - zipkin
#      networks:
#        - kafka-network
#
## Keycloak for JWT/OAuth2 (Alternative to building auth service)
#  keycloak:
#    image: quay.io/keycloak/keycloak:22.0.5
#    container_name: keycloak
#    environment:
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#      KC_DB: postgres
#      KC_DB_URL_HOST: postgres
#      KC_DB_URL_DATABASE: keycloakdb
#      KC_DB_USERNAME: keycloak
#      KC_DB_PASSWORD: password
#    ports:
#      - "8085:8080"
#    command: start-dev
#    depends_on:
#      - postgres
#    networks:
#      - kafka-network
#  
#  # PostgreSQL for Keycloak
#  postgres-keycloak:
#    image: postgres:15-alpine
#    container_name: postgres-keycloak
#    environment:
#      POSTGRES_DB: keycloakdb
#      POSTGRES_USER: keycloak
#      POSTGRES_PASSWORD: password
#    ports:
#      - "5433:5432"
#    networks:
#      - kafka-network

 #Nginx API Gateway
#   nginx-gateway:
#     image: nginx:alpine
#     container_name: nginx-gateway
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#       - ./nginx/conf.d:/etc/nginx/conf.d
#     depends_on:
#       - order-service
#       - inventory-service
#       - notification-service
#       - auth-service
#     networks:
#       - kafka-network
